/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jni_ParamJNI */

#ifndef _Included_com_jni_ParamJNI
#define _Included_com_jni_ParamJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jni_ParamJNI
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_jni_ParamJNI_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_jni_ParamJNI
 * Method:    concat
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jni_ParamJNI_concat
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
