/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jni_UserJNI */

#ifndef _Included_com_jni_UserJNI
#define _Included_com_jni_UserJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jni_UserJNI
 * Method:    createUse
 * Signature: (Ljava/lang/String;I)Lcom/jni/User;
 */
JNIEXPORT jobject JNICALL Java_com_jni_UserJNI_createUse
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_jni_UserJNI
 * Method:    toString
 * Signature: (Lcom/jni/User;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jni_UserJNI_toString
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
